name: plainliving
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  flutter_dotenv: ^5.0.2
  google_sign_in: ^6.2.2
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4
  firebase_storage: ^12.4.2
  readmore: ^3.0.0
  iconsax: ^0.0.8
  table_calendar: ^3.2.0
  fl_chart: ^0.68.0
  flutter_native_splash: ^2.4.4
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.2
  lottie: ^3.3.1
  smooth_page_indicator: ^1.2.0+3
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  image_cropper: ^9.0.0
  flutter_stripe: ^11.5.0
  flutter_local_notifications: ^19.1.0
  font_awesome_flutter: ^10.8.0
  modal_bottom_sheet: ^3.0.0
  animated_custom_dropdown: ^3.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logoL.png"
  image_path_android: "assets/icons/logoL.png"
  image_path_ios: "assets/icons/logoL.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/logoL.png"
  adaptive_icon_background_dark_mode: "#121212"
  adaptive_icon_foreground_dark_mode: "assets/icons/logoD.png"
  min_sdk_android: 33
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
